"""Generate SQL to load the issue catalog into Supabase forum_issues.

Reads data/forum/{model}/issue_catalog.json and emits an idempotent SQL file
that replaces all rows for the model. Run the SQL on prod via:

  ssh tsrm-prod "cd ~/app && PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 \
      -U postgres -d postgres -f scripts/<generated>.sql"

(REST ingest isn't used because the prod Supabase REST port isn't reachable
from the dev machine.)
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT_DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def slugify(text: str, maxlen: int = 70) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:maxlen].strip("-") or "issue"


def sql_str(s: str) -> str:
    """Single-quote a string for SQL (standard_conforming_strings on)."""
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="mk3")
    ap.add_argument("--catalog", default=None, help="Path to issue_catalog.json")
    ap.add_argument("--out", default=None, help="Output .sql path")
    args = ap.parse_args()

    base = ROOT_DATA_DIR / "forum" / args.model
    catalog_path = Path(args.catalog) if args.catalog else base / "issue_catalog.json"
    out_path = Path(args.out) if args.out else base / "issue_catalog.sql"

    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))

    seen: dict[str, int] = {}
    rows = []
    for c in catalog:
        issue = c["issue"]
        system = c["system"]
        base_slug = f"{slugify(system, 16)}-{slugify(issue)}"
        n = seen.get(base_slug, 0)
        seen[base_slug] = n + 1
        slug = base_slug if n == 0 else f"{base_slug}-{n+1}"

        threads = c.get("threads", [])
        # search text = issue + member titles + labels
        parts = [issue]
        for t in threads:
            parts.append(t.get("title", ""))
            if t.get("issue_label"):
                parts.append(t["issue_label"])
        search_text = " ".join(p for p in parts if p)

        rows.append({
            "slug": slug,
            "model": args.model,
            "system": system,
            "issue": issue,
            "thread_count": int(c.get("thread_count", len(threads))),
            "threads": threads,
            "search_text": search_text,
        })

    lines = [
        "-- Generated by forum_issues_ingest.py -- do not edit by hand.",
        "BEGIN;",
        f"DELETE FROM forum_issues WHERE model = {sql_str(args.model)};",
    ]
    for r in rows:
        threads_json = json.dumps(r["threads"], ensure_ascii=False)
        lines.append(
            "INSERT INTO forum_issues (slug, model, system, issue, thread_count, threads, search_text) VALUES ("
            f"{sql_str(r['slug'])}, {sql_str(r['model'])}, {sql_str(r['system'])}, "
            f"{sql_str(r['issue'])}, {r['thread_count']}, {sql_str(threads_json)}::jsonb, "
            f"{sql_str(r['search_text'])});"
        )
    lines.append("COMMIT;")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    n_threads = sum(r["thread_count"] for r in rows)
    print(f"Wrote {len(rows)} issues ({n_threads} thread links) -> {out_path}")


if __name__ == "__main__":
    main()
